credentials:
  usernames:
    aluno1:
      email: aluno1@example.com
      name: Aluno Um
      password: "$2b$12$EixZaYVK1QIIxMOux./c.Ou0K6Q./iy5HBX69evbj2/5YjB3Y5L/2" # Hashed password for 'abc'
    aluno2:
      email: aluno2@example.com
      name: Aluno Dois
      password: "$2b$12$EixZaYVK1QIIxMOux./c.Ou0K6Q./iy5HBX69evbj2/5YjB3Y5L/2" # Hashed password for 'abc'
cookie:
  expiry_days: 30
  key: some_signature_key # Chave secreta para assinar o cookie
  name: some_cookie_name
preauthorized:
  emails: []

